version: "3"
services:
  db:
    build:
      context: ./db
    expose:
      - 3306
    environment:
      MYSQL_USER: eins
      MYSQL_PASSWORD: zwei
      MYSQL_ROOT_PASSWORD: drei
      MYSQL_DATABASE: user_activity_logger

  user:
    build:
      context: ./user_service
    expose:
      - 9001
    environment:
      USER_PORT: ":9001"
      DB_DSN: "eins:zwei@tcp(db:3306)/user_activity_logger"
      DB_TABLE: "users"
    links:
      - db

  activity:
    build:
      context: ./activity_service
    expose:
      - 9002
    environment:
      ACTIVITY_PORT: ":9002"
      USER_PORT: "user:9001"
      DB_DSN: "eins:zwei@tcp(db:3306)/user_activity_logger"
      DB_TABLE: "activities"
    links:
      - db
      - user

  client:
    build:
      context: ./client
    environment:
      ACTIVITY_PORT: "activity:9002"
      USER_PORT: "user:9001"
    links:
      - user
      - activity
